# fly.toml file generated for your backend app

app = "terratechdb"   # change this to your Fly.io app name
primary_region = "sin"   # closest region, e.g., sin = Singapore (good for India)

[build]
  # Fly will auto-detect Dockerfile if present
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 5000        # your app's port inside container
  force_https = true
  auto_stop_machines = false  # keep running even when inactive
  auto_start_machines = true
  min_machines_running = 1    # ensures backend is always alive
  processes = ["app"]

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"
    restart_limit = 0
